plugins:
  slack_enabled:
    default: false
    validator: "DiscourseSlackEnabledSettingValidator"
  slack_incoming_webhook_token:
    default: ''
  slack_outbound_webhook_url:
    default: ''
  slack_discourse_username:
    default: system
  slack_discourse_excerpt_length:
    default: 400
  slack_icon_url:
    default: ''
  slack_access_token:
    default: ''
  post_to_slack_window_mins:
    default: 10